### ISSUE TITLE
Mixed encryption and hashing on DataBase security

### ISSUE THREAD

**Issue by swalahamani** [kcdp/kcdp.github.io#1]
"തീർച്ചയായും നിങ്ങളുടെ വിലപ്പെട്ട രേഖകൾ plain text ആയി ഡാറ്റബസുകളിൽ സൂക്ഷിക്കാറില്ല. നിങ്ങളുടെ വിലപ്പെട്ട രേഖകൾ അല്ലെങ്കിൽ പാസ്സ്‌വേർഡ് പോലെയുള്ള വാക്കുകൾ എല്ലാം തന്നെ (encrypt) ചെയ്തു (MD5, SHA1, MySQL, NTLM, SHA256, SHA512 ) ഉള്ള ഹാഷ്കളിലേക്ക് മാറ്റിയാണ് ഡാറ്റാബേസുകളിൽ സ്റ്റോർ ചെയ്യപ്പെടാറുള്ളത്. ഇനി ഡാറ്റ അടിച്ചുകൊണ്ടു പോയാലും കിട്ടിയ ഡാറ്റ വായിക്കണമെങ്കിൽ ഡിക്ര്യപ്ട് (decrypt) ചെയേണ്ടി വെറും. 128-bit key with modern hardware is going to take around 500 billion years. വരെ എടുക്കാം."

The algorithms you mentioned after saying about encryption are all hashing algorithms and not encryption algorithms. And I don't think there is an algorithm available in the name of "MySQL".

Anyway good job!

**Comment by bajpangosh** [comment]
MySQL5 മുകളില്‍ ഉള്ളവക്ക് ഉണ്ട്,  https://hashes.com/decrypt/basic
ref:- https://dev.mysql.com/doc/refman/5.6/en/password-hashing.html

**Comment by gautamkrishnar** [comment]
@swalahamani  Yes nice point encryption is a two way function, hashing is one way.

**Comment by gautamkrishnar** [comment]
@bajpangosh encryption and hashing are different: https://gcn.com/articles/2013/12/02/hashing-vs-encryption.aspx

**Comment by bajpangosh** [comment]
An attacker who steals a file of encrypted passwords might also steal the key.
Hashing is a better option, especially with the judicious use of salt. പോസ്റ്റില്‍ ചെറിയ മാറ്റം വരുത്താം. താങ്ക്സ്

**Comment by gautamkrishnar** [comment]
@bajpangosh  Also mysql is not a hasing algorith, if you meant `password` function please read about the function doc: https://dev.mysql.com/doc/refman/5.7/en/encryption-functions.html#function_password It is not meant to be used in production. Its used basicially to store mysql user passwords. In production we normally use other hashing algorithms instead of using passowrd function. 

Eg:
```sql
UPDATE table SET Password = MD5("password") WHERE ID="id";
````
