### ISSUE TITLE
വളരെ നല്ല ഒരു  ഇത് !

### ISSUE THREAD

**Issue by gautamkrishnar** [kcdp/kcdp.github.io#2]
കാര്യം അറിയാതെ ചിലക്കുന്ന ചിലരുടെ  വായ അടക്കാനും, കൂടുതൽ അറിയാൻ ആഗ്രഹിക്കുന്നവർക് കൂടുതൽ അറിയാനും ഉള്ള  വളരെ നല്ല മുതൽക്കൂട്ടാണ് ഈ സൈറ്റ്.... 

ഇതിന്റെ പിന്നിൽ പ്രവർത്തിക്കുന്ന എല്ലാർക്കും  എന്റെ അഭിനന്ദനങ്ങൾ.... ഇനി ഇപ്പോൾ ഗിറ്റ്  ഹബ്  അമേരിക്കൻ സൈറ്റ് ആണെന്ന് പറഞ്ഞു ആൾക്കാർ വരുമോ എന്തോ....? 😆

**Comment by bajpangosh** [comment]
Data സൂക്ഷിക്കുന്ന സെര്‍വര്‍ വരെ കാണിച്ചു കൊടുകേണ്ടി വരും എന്നുള്ള പേടി കൊണ്ട് Pure HTML ആണ് ഉപയോഗികേണ്ടി വന്നത്/

**Comment by nowfalsalahudeen** [comment]
ഗിതുബ്‌ ഇപോ മൈക്രോസോഫ്ട്‌ ന്റെ ഉടമസ്ഥതയില്‍ ഉള്ളതല്ലേ...അപോ ഒകെ ബൈ

**Comment by bajpangosh** [comment]
ഇജ്ജ്‌ മിണ്ടാതെ ഇരുന്നേ
